# WARNING - Generated by {fusen} from dev/flat_2.Rmd: do not edit by hand

#' Add a layer to your map, regarding a particular type of OSM key-value-geometry object.
#' @param basemap the basemap which you wish to add elements to
#' @param gosmdata the gosmdata element you wish to add to the map, as returned by pick_osmdata()
#' @param layergroup in which layer grouping elements should this gosmdata element be displayed (defaults to "additional")
#' @param color color of the data items
#' @return a leaflet map
#' @export
#' @examples
#' g_bridges=get_osmdata("man_made","bridge","confluence") %>%
#'   pick_osmdata(geom="osm_polygons") %>%
#'   detail_element()
#' g_parks=get_osmdata("leisure","park","confluence") %>%
#'   pick_osmdata(geom="osm_polygons") %>%
#'   detail_element()
#' map=base_map("confluence") %>%
#'   add_to_map(g_bridges) %>%
#'   add_to_map(g_parks, color="green")
#' map
#'
#' g_vineyard=get_osmdata("landuse","vineyard","condrieu") %>%
#'   pick_osmdata(geom="osm_polygons") %>%
#'   detail_element()
#' map=base_map("condrieu") %>%
#'   add_to_map(g_vineyard, color="purple")
#'
add_to_map <- function(basemap, gosmdata, layergroup="additional",color="red"){
  if(is.null(gosmdata)){
    return(basemap)
  }
  geom=gosmdata %>% sf::st_geometry_type() %>% unique() %>% .[1]
  if(geom=="POINT"){addShape=leaflet::addCircles}
  if(geom %in% c("POLYGON","MULTIPOLYGON")){addShape=leaflet::addPolygons}
  if(geom %in% c("LINESTRING","MULTILINESTRING")){addShape=leaflet::addPolylines}
  map=basemap %>%
    addShape(data=gosmdata,
             group=layergroup,
             color=color,
             popup=~detail
    )
}

